const base = new URL(`${import.meta.env.BASE_URL}assets/kenney/pixel-platformer`, window.location.href).toString().replace(/\/$/, '');

export const assetManifest = {
  base,
  tiles: {
    grassLeft: `${base}/Tiles/tile_0000.png`,
    grassMidA: `${base}/Tiles/tile_0001.png`,
    grassMidB: `${base}/Tiles/tile_0002.png`,
    grassRight: `${base}/Tiles/tile_0003.png`,
    dirtA: `${base}/Tiles/tile_0120.png`,
    dirtB: `${base}/Tiles/tile_0121.png`,
    dirtC: `${base}/Tiles/tile_0122.png`,
    dirtD: `${base}/Tiles/tile_0123.png`,
    question: `${base}/Tiles/tile_0010.png`,
    questionUsed: `${base}/Tiles/tile_0011.png`,
    block: `${base}/Tiles/tile_0009.png`,
    crate: `${base}/Tiles/tile_0047.png`,
    dirtLeft: `${base}/Tiles/tile_0048.png`,
    dirtRight: `${base}/Tiles/tile_0050.png`,
    redPlatformLeft: `${base}/Tiles/tile_0012.png`,
    redPlatformMid: `${base}/Tiles/tile_0014.png`,
    redPlatformRight: `${base}/Tiles/tile_0015.png`,
    coinA: `${base}/Tiles/tile_0151.png`,
    coinB: `${base}/Tiles/tile_0152.png`,
    cloudLeft: `${base}/Tiles/tile_0153.png`,
    cloudMidA: `${base}/Tiles/tile_0154.png`,
    cloudMidB: `${base}/Tiles/tile_0155.png`,
    cloudRight: `${base}/Tiles/tile_0156.png`,
    sign: `${base}/Tiles/tile_0084.png`,
    arrow: `${base}/Tiles/tile_0087.png`,
    arrowRight: `${base}/Tiles/tile_0088.png`,
    ladderTop: `${base}/Tiles/tile_0051.png`,
    ladder: `${base}/Tiles/tile_0071.png`,
    gem: `${base}/Tiles/tile_0067.png`,
    key: `${base}/Tiles/tile_0027.png`,
    springA: `${base}/Tiles/tile_0107.png`,
    springB: `${base}/Tiles/tile_0108.png`,
    flag: `${base}/Tiles/tile_0111.png`,
    pipeTopLeft: `${base}/Tiles/tile_0093.png`,
    pipeTopRight: `${base}/Tiles/tile_0094.png`,
    pipeBody: `${base}/Tiles/tile_0095.png`,
    bluePipeLeft: `${base}/Tiles/tile_0132.png`,
    bluePipeMidA: `${base}/Tiles/tile_0133.png`,
    bluePipeMidB: `${base}/Tiles/tile_0134.png`,
    bluePipeEnd: `${base}/Tiles/tile_0135.png`,
    plantA: `${base}/Tiles/tile_0124.png`,
    plantB: `${base}/Tiles/tile_0128.png`,
    plantC: `${base}/Tiles/tile_0129.png`,
    mushroom: `${base}/Tiles/tile_0128.png`,
    treeTop: `${base}/Tiles/tile_0097.png`,
    treeFruitA: `${base}/Tiles/tile_0098.png`,
    treeFruitB: `${base}/Tiles/tile_0099.png`,
    trunkA: `${base}/Tiles/tile_0136.png`,
    trunkB: `${base}/Tiles/tile_0137.png`,
    trunkC: `${base}/Tiles/tile_0138.png`,
    rock: `${base}/Tiles/tile_0068.png`,
    waterTop: `${base}/Tiles/tile_0033.png`,
    water: `${base}/Tiles/tile_0034.png`,
    waterfall: `${base}/Tiles/tile_0054.png`
  },
  characters: {
    player: `${base}/Tiles/Characters/tile_0000.png`,
    playerWalkA: `${base}/Tiles/Characters/tile_0001.png`,
    playerWalkB: `${base}/Tiles/Characters/tile_0002.png`,
    playerJump: `${base}/Tiles/Characters/tile_0003.png`,
    enemyA: `${base}/Tiles/Characters/tile_0015.png`,
    enemyB: `${base}/Tiles/Characters/tile_0017.png`,
    robotA: `${base}/Tiles/Characters/tile_0018.png`
  },
  backgrounds: {
    cloudA: `${base}/Tiles/Backgrounds/tile_0008.png`,
    cloudB: `${base}/Tiles/Backgrounds/tile_0009.png`
  }
} as const;

export type AssetKey = keyof typeof assetManifest.tiles | keyof typeof assetManifest.characters | keyof typeof assetManifest.backgrounds;
